# Generated by Django 5.1.4 on 2024-12-25 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 25, 11, 54, 33, 948895, tzinfo=datetime.timezone.utc)),
        ),
    ]
