# Generated by Django 5.1.4 on 2024-12-25 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 25, 18, 18, 6, 979306, tzinfo=datetime.timezone.utc)),
        ),
    ]
